packages:
  - name: k3s
    category: k8s
    version: "1.28.1-rc2+k3s1"
    k3s_version: "2"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
  - name: k3s
    category: k8s
    version: "1.26.6+1"
    k3s_version: "2"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
  - name: k3s
    category: k8s
    version: "1.27.3+1"
    k3s_version: "2"
    labels:
      github.owner: "k3s-io"
      github.repo: "k3s"
    uri:
      - https://github.com/k3s-io/k3s
    license: "APL-2"
    description: " Lightweight Kubernetes "
